name: Migration

on:
  pull_request:
  workflow_dispatch:
    inputs:
      branchName:
        description: 'The branch that contains the migration script. All branches will be based off this branch.'
        required: true
      scriptPath:
        description: 'Path to the migration script to run, relative to the repository root. Will be passed a glob pattern'
        required: true

jobs:
  teamOwners:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: codeowners-preview
        uses: ./
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          reviewerThreshold: 3
      - run: echo '${{ steps.codeowners-preview.outputs.teamOwners}}' | jq .

    outputs:
      teams: ${{ steps.codeowners-preview.outputs.teamOwners }}

  migrate:
    needs: teamOwners
    runs-on: ubuntu-latest
    strategy:
      matrix:
        bucket: ${{ fromJson(needs.teamOwners.outputs.teams) }}
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ matrix.bucket.team }}
      - run: |
          touch .${{ matrix.bucket.paths[0] }}foo.txt
          git add -A
          git commit -m "Test commit!"
          gh pr create --draft
